# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import face_recognition_pb2 as face__recognition__pb2


class FaceRecognitionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterFace = channel.unary_unary(
                '/face.FaceRecognition/RegisterFace',
                request_serializer=face__recognition__pb2.RegisterRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.RegisterReply.FromString,
                )
        self.RecognizeFace = channel.unary_unary(
                '/face.FaceRecognition/RecognizeFace',
                request_serializer=face__recognition__pb2.RecognizeRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.RecognizeReply.FromString,
                )


class FaceRecognitionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognitionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterFace,
                    request_deserializer=face__recognition__pb2.RegisterRequest.FromString,
                    response_serializer=face__recognition__pb2.RegisterReply.SerializeToString,
            ),
            'RecognizeFace': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeFace,
                    request_deserializer=face__recognition__pb2.RecognizeRequest.FromString,
                    response_serializer=face__recognition__pb2.RecognizeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'face.FaceRecognition', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognition(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face.FaceRecognition/RegisterFace',
            face__recognition__pb2.RegisterRequest.SerializeToString,
            face__recognition__pb2.RegisterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RecognizeFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/face.FaceRecognition/RecognizeFace',
            face__recognition__pb2.RecognizeRequest.SerializeToString,
            face__recognition__pb2.RecognizeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
