# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face_recognition.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61\x63\x65_recognition.proto\x12\x04\x66\x61\x63\x65\".\n\x0fRegisterRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\"1\n\rRegisterReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\"!\n\x10RecognizeRequest\x12\r\n\x05image\x18\x01 \x01(\t\"2\n\x0eRecognizeReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32\x8c\x01\n\x0f\x46\x61\x63\x65Recognition\x12:\n\x0cRegisterFace\x12\x15.face.RegisterRequest\x1a\x13.face.RegisterReply\x12=\n\rRecognizeFace\x12\x16.face.RecognizeRequest\x1a\x14.face.RecognizeReplyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_recognition_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTERREQUEST._serialized_start=32
  _REGISTERREQUEST._serialized_end=78
  _REGISTERREPLY._serialized_start=80
  _REGISTERREPLY._serialized_end=129
  _RECOGNIZEREQUEST._serialized_start=131
  _RECOGNIZEREQUEST._serialized_end=164
  _RECOGNIZEREPLY._serialized_start=166
  _RECOGNIZEREPLY._serialized_end=216
  _FACERECOGNITION._serialized_start=219
  _FACERECOGNITION._serialized_end=359
# @@protoc_insertion_point(module_scope)
